### ISSUE TITLE
Compatibility with hypothesis-phases argument

### ISSUE THREAD

**Issue by andrewlaguna824** [schemathesis/action#25]
Hello! I just started using schemathesis from the CLI with the `hypothesis-phases explicit` arg (required for my API). I tried setting this as an additional arg in the `args` option for the github action, but it does not look like it is respected.

Example yml:
```yaml
jobs:
  openapi_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: validate oas
        uses: schemathesis/action@v1
        with:
          schema: <redacted>
          base-url: <redacted>
          report: false
          checks: |
            not_a_server_error
            status_code_conformance
            content_type_conformance
            response_headers_conformance
            response_schema_conformance
            negative_data_rejection
          args: |
            --hypothesis-phases explicit
            -H "Accept: application/json"
```

Let me know if this is a known issue or if I should be handling this requirement in another way.

Thanks!
