### ISSUE TITLE
schemathesis/action@v1 keeps using --hypothesis-database

### ISSUE THREAD

**Issue by fernandatenorio** [schemathesis/action#29]
After the release 2.0 I started getting the error: Error: No such option: --hypothesis-database Did you mean --generation-database?

I am not explicitly using the command --hypothesis-database, however the action adds it to the executed command. See the log output:

```
Run source env/bin/activate
  source env/bin/activate
  schemathesis run \
    http://localhost:6010/swagger/v1/swagger.json \
    --hypothesis-database=:memory: \
    --hypothesis-max-examples=100 \
    --checks=all \
    --report=vcr --report-path=schemathesis-report.yaml \

```

This is my action on githubAction:
```
      - uses: schemathesis/action@v1
        with:
          schema: 'http://localhost:6010/swagger/v1/swagger.json'
          wait-for-schema: '30'
          args: '--report=vcr --report-path=schemathesis-report.yaml'
        continue-on-error: true
```

Also tried:
```
      - uses: schemathesis/action@v1
        with:
          schema: 'http://localhost:6010/swagger/v1/swagger.json'
          wait-for-schema: '30'
          args: '--cassette-path schemathesis-report.yaml --report=schemathesis-output.txt'
        continue-on-error: true
```
